# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

min_version = '2025.1.8'

[tools]
go = "1.25.3"
bun = "latest"
"aqua:dyne/slangroom-exec" = "latest"
goreleaser = "latest"
pre-commit = "latest"
