# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "credimi"
SPDX-PackageSupplier = "Forkbomb BV"
SPDX-PackageDownloadLocation = "https://github.com/ForkbombEu/credimi"

[[annotations]]
path = [
    ".env.example",
    ".idea/**/*",
    ".vscode/launch.json",
    ".vscode/settings.json",
    "config_templates/**/*",
    "docs/**/*",
    "fixtures/test_pb_data/types.d.ts",
    "go.sum",
    "mocked_templates/**/*",
    "pb_migrations/*",
    "pkg/credential_issuer/openid-credential-issuer.schema.go",
    "pkg/workflowengine/workflows/credentials_config/openid-credential-issuer.schema.go",
    "schemas/**/*",
    "test_pb_data/*",
    "VERSION",
    "webapp/.cursor/mcp.json",
    "webapp/.env.example",
    "webapp/.vscode/mcp.json",
    "webapp/.vscode/settings.json",
    "webapp/AGENTS.md",
    "webapp/bun.lock",
    "webapp/messages/**/*",
    "webapp/project.inlang/.gitignore",
    "webapp/project.inlang/project_id",
    "webapp/src/lib/content/**/*",
    "webapp/src/lib/types/openid-credential-issuer.ts",
    "webapp/src/lib/workflows/queries.test.json",
    "webapp/src/modules/components/ui/**/*",
    "webapp/src/modules/i18n/paraglide/.gitignore",
    "webapp/src/modules/i18n/paraglide/.prettierignore",
    "webapp/static/emails/_emailData.d.ts",
    "webapp/static/hero.png",
    "webapp/static/pages/**/*",
]
precedence = "override"
SPDX-FileCopyrightText = "Forkbomb BV"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["deployment/grafana/**/*", "deployment/thirdparty-simulator/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "temporal.io"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["pkg/internal/canonify/testdata/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2020 Max Woolf"
SPDX-License-Identifier = "MIT"
