services:
  temporal:
    image: temporalio/temporal:latest
    command: server start-dev --ip 0.0.0.0 --port 7777
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/127.0.0.1/7777'"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SERVICE_FQDN_TEMPORAL_7777
      - SERVICE_FQDN_TEMPORALUI_8777
