# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# name: ğŸŒ webapp tests
#
# on:
#   pull_request:
#     paths:
#       - ".github/workflows/webapp.yml"
#       - "webapp/**"
#
# jobs:
#   test:
#     name: Webapp unit tests
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v5
#         with:
#           persist-credentials: false
#       - uses: oven-sh/setup-bun@v2
#         with:
#           bun-version: latest
#       - name: Install dependencies
#         run: bun i
#         working-directory: webapp
#       - name: Run unit tests
#         run: bun run test:unit -- --run
#         working-directory: webapp

